    <div class="left">
      <a href="https://matrixim.cc">matrixim.cc</a> |
      <a href="https://blogs.cnjabber.net">cnjabber blogs</a> |
      <a href="https://vimacs.cnjabber.net">vimacs's articles</a>
    </div>

    <div class="right">
      <span class="doNotDisplay">Related sites:</span>
      | <a href="https://xmpp.org">XMPP</a>
      | <a href="https://matrix.org">Matrix</a>
      | <a href="https://www.bdwm.net/v2/thread.php?bid=13">linux.bdwm.net</a>
      | <a href="https://blug.sh">Beijing LUG</a>
      | <a href="https://szdiy.org">SZDIY</a>
      | <a href="http://getgnulinux.org">Get GNU/Linux</a>
      | <a href="http://www.theopendisc.com/">OpenDisc</a>
      | <a href="/sitemap">site map</a>
    </div>

